### user registration
POST http://localhost:4000/user-api/register
Content-Type: application/json

{
    "usertype":"user",
    "username":"Kitta",
    "password":"krishna",
    "email":"krishna@gmail.com"
}

### user Login
POST http://localhost:4000/user-api/login
Content-Type: application/json

{
    "usertype":"user",
    "username":"Kitta",
    "password":"krishna"
}

###author registration
POST http://localhost:4000/author-api/register
Content-Type: application/json

{
    "usertype":"author",
    "username":"Nalla",
    "password":"NallaReddy",
    "email":"anirudh@gmail.com"
}

### Author Login
POST http://localhost:4000/author-api/login
Content-Type: application/json

{
    "usertype":"author",
    "username":"Nalla",
    "password":"NallaReddy"
}


### add a new article:

POST http://localhost:4000/author-api/new-article
Content-Type: application/json

{
    "article": "{{$timestamp}}",
    "title": "Fundamentals of JS",
    "category": "Programming",
    "content": "foiurwhfv;ioeruvnrliuvb iufeliuvn liwu b iubli ubfiubwf iubffiyub4wiyfbiy i ybib wib wifbw4ifbrib",
    "dateOfCreation": "{{$datetime iso8601}}",
    "dateOfModification": "{{$datetime iso8601}}",
    "username": "Nalla",
    "comments": [],
    "status": true
}

### read articles by author's username

GET http://localhost:4000/author-api/articles/Nalla


### Edit Articles

PUT http://localhost:4000/author-api/article
Content-Type: application/json

{
    "article": "1718681503",
    "title": "Fundamentals of JS",
    "category": "Programming",
    "content": "foiurwhfv;ioeruvnrliuvb iufeliuvn liwu b iubli ubfiubwf iubffiyub4wiyfbiy i ybib wib wifbw4ifbrib",
    "dateOfCreation": "2024-06-18T03:31:43.595Z",
    "dateOfModification": "{{$datetime iso8601}}",
    "username": "Nalla",
    "comments": [],
    "status": true
}